name: brianfinchphotography
favicon: null
layout_spectrum: 0.2680423161946237
typography_spectrum: 0.9356648123357445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9097116079647094
  lightness: 0.12111690454185009
  saturation: 0.8457079769577831
  rhythmicContrast: 0.060663102427497506
purpose: []
